### ISSUE TITLE
Backend is not working

### ISSUE THREAD

**Issue by VitaliyBelyaev** [Fi5t/workshop-devfest-2020#2]
Hi! Thank you for this workshop.

I'm starting to pass it and faced the problem that backend https://vulnerable-backend.herokuapp.com/api/v1/ for this workshop responds with error. 

I thought that I may create my own backend with my account on Heroku using python code for the backend from this repository.

Could you please provide some instructions how to setup that backend using Dockerfile(that exists in `vulnerable-backend` dir) in Heroku, or links to resources where I should look first?

**Comment by VitaliyBelyaev** [comment]
Thank you for your answer! I'll try to run it on the local machine with Docker.

**Comment by VitaliyBelyaev** [comment]
I made it like this:
1. Open `vulnerable-backend` directory in VSCode
2. Change `$PORT` to `3000` in `Dockerfile` that is located in `vulnerable-backend`  directory
3. In terminal cd to `vulnerable-backend` directory and run `docker build -t vulnerable-backend. `
4. Then in terminal run `docker run -dp 3000:3000 vulnerable-backend`
5. Through Docker desktop app you could see that container is running
6. Then go to AS with `vulnerable-app` open
7. Change 53 line in `AppModule.kt` from `.baseUrl("https://vulnerable-backend.herokuapp.com/api/v1/")` to `.baseUrl("http://[ip-address-of-your-pc]:3000/api/v1/")`
8. Ensure that your device and PC is connected to the same Wi-fi network
9. Enjoy working backend on your local machine

More info about Docker build and run commands [here](https://docs.docker.com/get-started/02_our_app/)

**Comment by VitaliyBelyaev** [comment]
Also using https scheme in base url not working. I suppose that is related to some TLS certificates configuration that I need to do in my locally hosted backend. 
@Fi5t maybe you can guide me in the right direction where to start?

**Comment by Fi5t** [comment]
Configuring TLS can be a bit tricky. The easiest way is to place your backend behind Nginx and configure HTTPS there. This [tutorial](https://stackify.com/how-to-configure-https-for-an-nginx-docker-container/) can help. Good luck =)
